### PR TITLE
Delete record & backup csv configuration

### PR DESCRIPTION
**Pull request by LuigiMasini**
Changes:
- Added a flag `--delete` to delete a record specified with `--name` and `--oldvalue`.
- Added a flag `--backup-csv` to download the register.it DNS csv configuration files before and after modification (will override previously written files).
- Added a help command `--help` .
- Updated the querySelector for the cookie popup.
- Updated the matching condition for updating / deleting a record.

### CODE REVIEW

**Comment by TheJoin95** [comment]
Thanks for the contribution; could you add some screenshot (with data obfuscation) to the PR description?

**Comment by LuigiMasini** [comment]
I'm not sure what screenshot I should take, hope these are ok.

Here's some screenshots for the delete process:

delete record button
confirm record deletion button


Screenshot for the download csv button:

download csv button


Help command screenshot:

help command

**Comment by TheJoin95** [comment]
I meant to provide screenshot from the script running in not headless mode to verify that everything was working fine.

It seems looking good then!

**Review by TheJoin95 — APPROVED** [review]

**Comment by LuigiMasini** [comment]
Thank you!

**Pull request merged**
